### ISSUE TITLE
memfault_http_task.c -Wstringop-overread build warning with GCC 11

### ISSUE THREAD

**Issue by vmedcy** [memfault/mtb-example-memfault#4]
GCC 11 emits -Wstringop-overread warning for memfault_http_task.c:

```
    Compiling app file memfault_http_task.c
source/memfault_http_task.c: In function 'prv_auto_connect_to_ap':
source/memfault_http_task.c:127:14: warning: 'strnlen' specified bound 64 exceeds source size 9 [-Wstringop-overread]
  127 |   } else if (strnlen(WIFI_SSID, MEMFAULT_WIFI_CONFIG_MAX_SIZE) > 0 &&
```

Steps to reproduce:
- Download and install GCC 11.3 from https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads
- Set WiFi SSID and password in source/memfault_example_app.h
- make build CY_COMPILER_GCC_ARM_DIR=C:/path/to/gcc11

**Comment by noahp** [comment]
Thanks for reporting this @vmedcy ! It's been patched in #5.
