### ISSUE TITLE
Warnings in source files

### ISSUE THREAD

**Issue by ddka22** [memfault/mtb-example-memfault#6]
The file "memfault_example_app.h" contains macros WIFI_SSID, WIFI_AUTH_TYPE, WIFI_PASSWORD, and MEMFAULT_PROJECT_KEY that are commented out which results in warnings during the build. There are other warnings as seen in the image attached.

Can you please provide default values to these macros and resolve these warnings? The ReadMe provides instructions to the users to fill it in for proper working of the code example, so we don't need to issue any warnings.

![mtb-example-memfault](https://user-images.githubusercontent.com/57934845/233715291-3279a279-5a9a-4395-a5a4-c065c650cc5d.PNG)

**Comment by steverae-work** [comment]
My suggestion was to update the Makefile, so that it could
dynamically define the macros only when building on automation ( which will suppress the warnings),
but leave the macros undefined for all other use-cases (the current behavior) :

```
ifneq ($(CI),)
$(shell echo '#define WIFI_SSID             "FILLMEIN"'          >  memfault_example_app_config.h)
$(shell echo '#define WIFI_AUTH_TYPE        "FILLMEIN"'          >> memfault_example_app_config.h)
$(shell echo '#define WIFI_PASSWORD         "FILLMEIN"'          >> memfault_example_app_config.h)
$(shell echo '#define MEMFAULT_PROJECT_KEY  "YOUR_PROJECT_KEY"'  >> memfault_example_app_config.h)
endif
```

note: ${CI} _is_ defined inside all GitLab CI/CD jobs, and in all "GitHub Actions workflow runs", and in all Jenkins jobs.

**Comment by ddka22** [comment]
@steverae-work the code example should not have anything that's not related to the application. So, I'm against adding this variable which will confuse users about its significance w.r.t the application.

**Comment by ejohnso49** [comment]
@ddka22 thanks for opening this issue. I will begin work on this. Thanks!
